# Generated by Django 6.0.3 on 2026-03-07 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("up", "Up"), ("down", "Down"), ("both", "Both")],
                        default="both",
                        max_length=10,
                    ),
                ),
                ("min_revision_count", models.PositiveSmallIntegerField(default=3)),
                ("lookback_days", models.PositiveSmallIntegerField(default=5)),
                (
                    "min_revision_ratio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "immediate_revision_ratio",
                    models.DecimalField(decimal_places=2, default=20, max_digits=7),
                ),
                ("distinct_brokerage_only", models.BooleanField(default=True)),
                ("watchlist_only", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AlertEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("up", "Up"), ("down", "Down"), ("both", "Both")],
                        max_length=10,
                    ),
                ),
                ("revision_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "distinct_brokerage_count",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "average_revision_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "max_revision_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                ("summary", models.TextField()),
                ("dedupe_key", models.CharField(max_length=64, unique=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("delivery_error", models.TextField(blank=True)),
                (
                    "security",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_events",
                        to="research.security",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="alerts.alertrule",
                    ),
                ),
            ],
            options={
                "ordering": ["-triggered_at"],
            },
        ),
    ]
