# Generated by Django 6.0.3 on 2026-03-07 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brokerage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(blank=True, max_length=30)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Security",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("market", models.CharField(blank=True, max_length=30)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["symbol"],
            },
        ),
        migrations.CreateModel(
            name="Analyst",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brokerage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analysts",
                        to="research.brokerage",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ResearchReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("naver", "Naver Research"),
                            ("csv", "CSV Import"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_report_id", models.CharField(blank=True, max_length=120)),
                ("title", models.CharField(max_length=255)),
                ("report_date", models.DateField()),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("target_price", models.BigIntegerField(blank=True, null=True)),
                (
                    "previous_target_price",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "eps_forecast",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("opinion", models.CharField(blank=True, max_length=50)),
                ("report_url", models.URLField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analyst",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="research.analyst",
                    ),
                ),
                (
                    "brokerage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="research.brokerage",
                    ),
                ),
                (
                    "security",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="research.security",
                    ),
                ),
            ],
            options={
                "ordering": ["-report_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WatchlistEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priority", models.PositiveSmallIntegerField(default=3)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "security",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="research.security",
                    ),
                ),
            ],
            options={
                "verbose_name": "Watchlist Entry",
                "verbose_name_plural": "Watchlist Entries",
                "ordering": ["priority", "security__symbol"],
            },
        ),
        migrations.AddConstraint(
            model_name="analyst",
            constraint=models.UniqueConstraint(
                fields=("brokerage", "name"), name="unique_analyst_per_brokerage"
            ),
        ),
        migrations.AddIndex(
            model_name="researchreport",
            index=models.Index(
                fields=["security", "report_date"],
                name="research_re_securit_b21c8e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="researchreport",
            index=models.Index(
                fields=["brokerage", "report_date"],
                name="research_re_brokera_b35778_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="researchreport",
            index=models.Index(
                fields=["published_at"], name="research_re_publish_ecf99d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="researchreport",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_report_id", ""), _negated=True),
                fields=("source", "source_report_id"),
                name="unique_source_report_id",
            ),
        ),
    ]
